### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by jeremyworger** [ben-hayes/catecophony#1]
Hey there, this looks really sweet. 
Is there any plan of building a windows vst in the future per chance?

Jeremy

**Comment by ben-hayes** [comment]
Hey @jeremydeanw :) thanks for the kind words.

I don't plan to run off a Windows build myself for the time being, as I don't have access to a Windows machine. But as far as I'm aware there's nothing platform specific in this implementation so it should build on Windows with no problem, if you're willing to give it a shot!

**Comment by jeremyworger** [comment]
Thanks for getting back to me, 
Would I build it in visual studio? It's been a while since I've built from source, not much of a coder really

**Comment by jeremyworger** [comment]
I managed to turn my other laptop into a hackintosh, so I can run it now :)
